apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-node-mongo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-node-mongo-app
  template:
    metadata:
      labels:
        app: devops-node-mongo-app
    spec:
      containers:
      - name: devops-node-mongo-app
        image: shayanzzzz/devops-node-mongo-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/devops-node-mongo-app"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-node-mongo-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
  selector:
    app: devops-node-mongo-app